name = "SoEwald2D"
uuid = "0daaa638-a47d-40d8-b855-b9e525a61752"
authors = ["Xuanzhao Gao"]
version = "0.1.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ExTinyMD = "fec76197-d59f-46dd-a0ed-76a83c21f7aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuasiEwald = "983f8767-50b7-4083-a328-dfb7a9c26de7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
Enzyme = "=0.11.6"
ExTinyMD = "0.2.1"
ForwardDiff = "0.10.36"
GaussQuadrature = "0.5.8"
QuasiEwald = "0.2.1"
SpecialFunctions = "2.3.1"
StatsBase = "0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
